steps:
- name: gcr.io/cloud-builders/bazel
  args: [
    '--host_jvm_args=-Dbazel.DigestFunction=SHA256',
    'test',
    '--auth_enabled=true',
    '--experimental_strict_action_env',
    '--remote_instance_name=projects/cst-c-prod-0',
    '--remote_local_fallback=false',
    '--remote_timeout=3600',
    '--spawn_strategy=remote',
    '--strategy=Javac=remote',
    '--strategy=Closure=remote',
    '--genrule_strategy=remote',
    '--define=EXECUTOR=remote',
    '--test_output=all',
    '--tls_enabled=true',
    '--verbose_failures=true',
    '--keep_going',
    '--experimental_remote_platform_override=properties:{ name:"container-image" value:"docker://gcr.io/asci-toolchain/nosla-debian8-clang-fl@sha256:e79e367aab94c6f18a0b39950fe4f160fda07ee01e3c32604c5f8472afa7c1f0" }',
    '--remote_cache=remotebuildexecution.googleapis.com',
    '--remote_executor=remotebuildexecution.googleapis.com',
    '//...'
  ]